import { expect, test } from '@playwright/test'
import { z } from 'zod'

test('real tenant owner issues a restricted key, rotates, revokes and reads safe audit', async ({ page }, info) => {
  const token = process.env['IOLINK_M6D_TOKEN']
  if (!token) throw new TypeError('IOLINK_M6D_TOKEN is required')
  await page.addInitScript(value => {
    localStorage.setItem('iolink.admin.token', value)
    localStorage.setItem('iolink.admin.expires_at', String(Date.now() + 3600_000))
  }, token)
  await page.goto('/system')
  const panel = page.getByRole('region', { name: '开放平台 API Key', exact: true })
  await expect(panel.locator('.el-loading-mask')).toHaveCount(0)
  const apiHeaders = { Authorization: `Bearer ${token}` }
  const emptyKeys = await page.request.get('/admin/v1/api-keys', { headers: apiHeaders })
  expect(await emptyKeys.json()).toEqual([])
  const emptyAudit = await page.request.get('/admin/v1/api-keys/audit', { headers: apiHeaders })
  expect(await emptyAudit.json()).toEqual([])
  const invalidField = await page.request.post('/admin/v1/api-keys', { headers: apiHeaders, data: { name: 'wrong-field', scopes: ['ponds:read'], resources: { farmIds: [8301] } } })
  expect(invalidField.status()).toBe(400)
  for (const resources of [{ farm_ids: [0] }, { farm_ids: [-1] }, { pond_ids: [0] }, { device_nos: [''] }, { farm_ids: null }, { pond_ids: null }, { device_nos: null }, null]) {
    const invalid = await page.request.post('/admin/v1/api-keys', { headers: apiHeaders, data: { name: 'invalid-resource', scopes: ['ponds:read'], resources } })
    expect(invalid.status()).toBe(400)
  }
  for (const resources of [{ farm_ids: [8303] }, { pond_ids: [8303] }, { device_nos: ['m6d-foreign'] }]) {
    const foreign = await page.request.post('/admin/v1/api-keys', { headers: apiHeaders, data: { name: 'foreign-resource', scopes: ['ponds:read'], resources } })
    expect(foreign.status()).toBe(404)
  }
  let issueRequests = 0
  page.on('request', request => { if (request.url().endsWith('/admin/v1/api-keys') && request.method() === 'POST') issueRequests++ })
  await panel.getByPlaceholder('Key 名称').fill('browser-live')
  await panel.getByPlaceholder('农场 ID（逗号分隔，可选）').fill('8301x')
  await panel.getByRole('button', { name: '签发 Key' }).click()
  await expect(page.getByText('资源 ID 必须是逗号分隔的正整数，请检查输入')).toBeVisible()
  const unchanged = await page.request.get('/admin/v1/api-keys', { headers: apiHeaders })
  expect(await unchanged.json()).toEqual([])
  expect(issueRequests).toBe(0)
  await panel.getByPlaceholder('农场 ID（逗号分隔，可选）').fill('')
  for (const malformed of [',', ', ,', 'm6d-allowed,']) {
    await panel.getByPlaceholder('设备号（逗号分隔，可选）').fill(malformed)
    await panel.getByRole('button', { name: '签发 Key' }).click()
    await expect(page.getByText('设备号须用逗号分隔，不能有空项，最多 100 个')).toBeVisible()
    expect(await (await page.request.get('/admin/v1/api-keys', { headers: apiHeaders })).json()).toEqual([])
    expect(issueRequests).toBe(0)
    await expect(page.getByText('设备号须用逗号分隔，不能有空项，最多 100 个')).toHaveCount(0)
  }
  await panel.getByPlaceholder('农场 ID（逗号分隔，可选）').fill('8301')
  await panel.getByPlaceholder('池塘 ID（逗号分隔，可选）').fill('8301')
  await panel.getByPlaceholder('设备号（逗号分隔，可选）').fill('m6d-allowed')
  await panel.getByText('设备读取', { exact: true }).click()
  await panel.getByText('报警读取', { exact: true }).click()
  await expect(panel.getByRole('checkbox', { name: '设备读取' })).not.toBeChecked()
  await expect(panel.getByRole('checkbox', { name: '报警读取' })).not.toBeChecked()
  const creation = page.waitForResponse(r => r.url().endsWith('/admin/v1/api-keys') && r.request().method() === 'POST')
  await panel.getByRole('button', { name: '签发 Key' }).click()
  const issued = await creation
  expect(issued.status()).toBe(201)
  const issuedSchema = z.object({ key: z.object({ key_id: z.string(), scopes: z.array(z.string()), resources: z.object({ farm_ids: z.array(z.number()), pond_ids: z.array(z.number()), device_nos: z.array(z.string()) }) }), secret: z.string() })
  const data = issuedSchema.parse(await issued.json())
  expect(data.key.scopes).toEqual(['ponds:read'])
  expect(data.key.resources).toEqual({ farm_ids: [8301], pond_ids: [8301], device_nos: ['m6d-allowed'] })
  expect(await panel.locator('code').textContent() === data.secret).toBe(true)
  for (const width of [375, 768, 1440]) {
    await page.setViewportSize({ width, height: 960 })
    await page.screenshot({ path: info.outputPath(`key-issued-${width}.png`), fullPage: true, animations: 'disabled', mask: [panel.locator('.el-alert')] })
    await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  }
  await page.reload()
  await expect(panel.locator('code')).toHaveCount(0)
  const keyTable = panel.locator('.el-table').first()
  const row = keyTable.getByRole('row', { name: new RegExp(data.key.key_id) })
  await expect(row.getByRole('cell', { name: 'ponds:read', exact: true })).toBeVisible()
  const rotation = page.waitForResponse(r => r.url().endsWith('/rotate'))
  await row.getByRole('button', { name: '轮换' }).click()
  const rotated = issuedSchema.parse(await (await rotation).json())
  expect(rotated.key.key_id).not.toBe(data.key.key_id)
  expect(rotated.secret === data.secret).toBe(false)
  await expect(row).toContainText('已撤销')
  const fresh = keyTable.getByRole('row', { name: new RegExp(rotated.key.key_id) })
  await fresh.getByRole('button', { name: '撤销' }).click()
  await expect(fresh).toContainText('已撤销')
  await page.getByRole('link', { name: '开放平台日志' }).click()
  await expect(page.getByRole('heading', { name: '开放平台操作日志' })).toBeVisible()
  for (const action of ['api_key.issued', 'api_key.rotated', 'api_key.revoked']) await expect(page.getByRole('cell', { name: action, exact: true })).toBeVisible()
  expect((await page.locator('body').textContent())?.includes(data.secret)).toBe(false)
  const audit = await page.request.get('/admin/v1/api-keys/audit', { headers: apiHeaders })
  const safeAudit = await audit.text()
  expect(safeAudit.includes(data.secret) || safeAudit.includes(rotated.secret)).toBe(false)
  await page.screenshot({ path: info.outputPath('audit.png'), fullPage: true })
})
